Remove-Item $env:USERPROFILE\.nuget\packages\app.metrics\ -Recurse -ErrorAction SilentlyContinue
Remove-Item $env:USERPROFILE\.nuget\packages\app.metrics.abstractions\ -Recurse -ErrorAction SilentlyContinue
Remove-Item $env:USERPROFILE\.nuget\packages\app.metrics.appnetcore\ -Recurse -ErrorAction SilentlyContinue
Remove-Item $env:USERPROFILE\.nuget\packages\app.metrics.aspnetcore\ -Recurse -ErrorAction SilentlyContinue
Remove-Item $env:USERPROFILE\.nuget\packages\app.metrics.aspnetcore.abstractions\ -Recurse -ErrorAction SilentlyContinue
Remove-Item $env:USERPROFILE\.nuget\packages\app.metrics.aspnetcore.core\ -Recurse -ErrorAction SilentlyContinue
Remove-Item $env:USERPROFILE\.nuget\packages\app.metrics.aspnetcore.endpoints\ -Recurse -ErrorAction SilentlyContinue
Remove-Item $env:USERPROFILE\.nuget\packages\app.metrics.aspnetcore.hosting\ -Recurse -ErrorAction SilentlyContinue
Remove-Item $env:USERPROFILE\.nuget\packages\app.metrics.aspnetcore.mvc\ -Recurse -ErrorAction SilentlyContinue
Remove-Item $env:USERPROFILE\.nuget\packages\app.metrics.aspnetcore.mvc.core\ -Recurse -ErrorAction SilentlyContinue
Remove-Item $env:USERPROFILE\.nuget\packages\app.metrics.aspnetcore.reporting\ -Recurse -ErrorAction SilentlyContinue
Remove-Item $env:USERPROFILE\.nuget\packages\app.metrics.aspnetcore.routing\ -Recurse -ErrorAction SilentlyContinue
Remove-Item $env:USERPROFILE\.nuget\packages\app.metrics.aspnetcore.tracking\ -Recurse -ErrorAction SilentlyContinue
Remove-Item $env:USERPROFILE\.nuget\packages\app.metrics.concurrency\ -Recurse -ErrorAction SilentlyContinue
Remove-Item $env:USERPROFILE\.nuget\packages\app.metrics.core\ -Recurse -ErrorAction SilentlyContinue
Remove-Item $env:USERPROFILE\.nuget\packages\app.metrics.extensions.configuration\ -Recurse -ErrorAction SilentlyContinue
Remove-Item $env:USERPROFILE\.nuget\packages\app.metrics.extensions.collectors\ -Recurse -ErrorAction SilentlyContinue
Remove-Item $env:USERPROFILE\.nuget\packages\app.metrics.extensions.dependencyinjection\ -Recurse -ErrorAction SilentlyContinue
Remove-Item $env:USERPROFILE\.nuget\packages\app.metrics.extensions.healthchecks\ -Recurse -ErrorAction SilentlyContinue
Remove-Item $env:USERPROFILE\.nuget\packages\app.metrics.extensions.hosting\ -Recurse -ErrorAction SilentlyContinue
Remove-Item $env:USERPROFILE\.nuget\packages\app.metrics.formatters.ascii\ -Recurse -ErrorAction SilentlyContinue
Remove-Item $env:USERPROFILE\.nuget\packages\app.metrics.formatters.grafanacloudhostedmetrics\ -Recurse -ErrorAction SilentlyContinue
Remove-Item $env:USERPROFILE\.nuget\packages\app.metrics.formatters.graphite\ -Recurse -ErrorAction SilentlyContinue
Remove-Item $env:USERPROFILE\.nuget\packages\app.metrics.formatters.influxdb\ -Recurse -ErrorAction SilentlyContinue
Remove-Item $env:USERPROFILE\.nuget\packages\app.metrics.formatters.json\ -Recurse -ErrorAction SilentlyContinue
Remove-Item $env:USERPROFILE\.nuget\packages\app.metrics.formatters.prometheus\ -Recurse -ErrorAction SilentlyContinue
Remove-Item $env:USERPROFILE\.nuget\packages\app.metrics.formatting.datadog\ -Recurse -ErrorAction SilentlyContinue
Remove-Item $env:USERPROFILE\.nuget\packages\app.metrics.reporting.console\ -Recurse -ErrorAction SilentlyContinue
Remove-Item $env:USERPROFILE\.nuget\packages\app.metrics.reporting.datadog\ -Recurse -ErrorAction SilentlyContinue
Remove-Item $env:USERPROFILE\.nuget\packages\app.metrics.reporting.grafanacloudhostedmetrics\ -Recurse -ErrorAction SilentlyContinue
Remove-Item $env:USERPROFILE\.nuget\packages\app.metrics.reporting.graphite\ -Recurse -ErrorAction SilentlyContinue
Remove-Item $env:USERPROFILE\.nuget\packages\app.metrics.reporting.http\ -Recurse -ErrorAction SilentlyContinue
Remove-Item $env:USERPROFILE\.nuget\packages\app.metrics.reporting.influxdb\ -Recurse -ErrorAction SilentlyContinue
Remove-Item $env:USERPROFILE\.nuget\packages\app.metrics.reporting.socket\ -Recurse -ErrorAction SilentlyContinue
Remove-Item $env:USERPROFILE\.nuget\packages\app.metrics.reporting.textfile\ -Recurse -ErrorAction SilentlyContinue
Remove-Item $env:USERPROFILE\.nuget\packages\app.metrics.extensions.nservicebus\ -Recurse -ErrorAction SilentlyContinue
Remove-Item $env:USERPROFILE\.nuget\packages\app.metrics.app.all\ -Recurse -ErrorAction SilentlyContinue
Remove-Item $env:USERPROFILE\.nuget\packages\app.metrics.aspnetcore.all\ -Recurse -ErrorAction SilentlyContinue
Remove-Item $env:USERPROFILE\.nuget\packages\app.metrics.datadog\ -Recurse -ErrorAction SilentlyContinue
Remove-Item $env:USERPROFILE\.nuget\packages\app.metrics.grafanacloudhostedmetrics\ -Recurse -ErrorAction SilentlyContinue
Remove-Item $env:USERPROFILE\.nuget\packages\app.metrics.graphite\ -Recurse -ErrorAction SilentlyContinue
Remove-Item $env:USERPROFILE\.nuget\packages\app.metrics.influxdb\ -Recurse -ErrorAction SilentlyContinue
Remove-Item $env:USERPROFILE\.nuget\packages\app.metrics.prometheus\ -Recurse -ErrorAction SilentlyContinue