{
 "title": "NServiceBus",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "influxdb" },
   {
    "name": "environment",
    "query": "SHOW TAG VALUES WITH KEY = \"env\""
   },
   {
    "name": "endpoint",
    "query": "SHOW TAG VALUES WITH KEY = \"endpoint\""
   },
   {
    "name": "server",
    "query": "SHOW TAG VALUES WITH KEY = \"server\""
   },
   {
    "name": "summarize",
    "query": "5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Critical Time",
   "type": "graph",
   "description": "### Critical Time\n\nCritical time is the time between when a message is sent and when it is fully processed. It is a combination of:\n\n**Network send time:** The time a message spends on the network before arriving in the destination queue\n\n**Queue wait time:** The time a message spends in the destination queue before being picked up and processed\n\n**Processing time:** The time it takes for the destination endpoint to process the message\n\nNServiceBus Duration Probe: Critical Time",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "last",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "nservicebus__critical_time",
     "select": [
      [
       { "params": [ "last" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "endpoint", "operator": "=~", "value": "/^$endpoint$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    },
    {
     "alias": "95th percentile",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "nservicebus__critical_time",
     "select": [
      [
       { "params": [ "p95" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "endpoint", "operator": "=~", "value": "/^$endpoint$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    },
    {
     "alias": "99th percentile",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "nservicebus__critical_time",
     "select": [
      [
       { "params": [ "p99" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "endpoint", "operator": "=~", "value": "/^$endpoint$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Fetch Rate by Message Type",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_messagetype",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "messagetype" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "nservicebus__messages_pulled_from_input_queue",
     "select": [
      [
       { "params": [ "rate5m" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "endpoint", "operator": "=~", "value": "/^$endpoint$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Processing Time",
   "type": "graph",
   "description": "### Processing Time\n\nProcessing time is the time it takes for an endpoint to invoke all handlers and sagas for a single incoming message.\n\nNServiceBus Duration Probe: Processing Time",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "last",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "nservicebus__processing_time",
     "select": [
      [
       { "params": [ "last" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "endpoint", "operator": "=~", "value": "/^$endpoint$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    },
    {
     "alias": "95th percentile",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "nservicebus__processing_time",
     "select": [
      [
       { "params": [ "p95" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "endpoint", "operator": "=~", "value": "/^$endpoint$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    },
    {
     "alias": "99th percentile",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "nservicebus__processing_time",
     "select": [
      [
       { "params": [ "p99" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "endpoint", "operator": "=~", "value": "/^$endpoint$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Success by Message Type",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_messagetype",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "messagetype" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "nservicebus__messages_successfully_processed",
     "select": [
      [
       { "params": [ "rate5m" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "endpoint", "operator": "=~", "value": "/^$endpoint$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Rates",
   "type": "graph",
   "description": "### Fetch Rate\n\nThis metric measures the number of messages that the endpoint reads from it's input queue regardless of whether message processing succeeds or fails.\n\nNServiceBus Signal Probe: # of msgs pulled from the input queue /sec\n\n###  Success Rate\n\nThis metric measures the number of messages that the endpoint successfully processes. In order for a message to be counted by this metric, all handlers must have executed without throwing an exception.\n\nNServiceBus Signal Probe: # of msgs successfully processed / sec\n\n###  Failure Rate\n\nThis metric measures the number of messages that the endpoint has failed to process. In order for a message to be counted by this metric, at least one handler must have thrown an exception.\n\nNServiceBus Signal Probe: # of msgs failures / sec\n\n### Retries\n\nThis metric measures the number of retries scheduled by the endpoint (immediate or delayed).\n\nNServiceBus Signal Probe: Retries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Retries",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "nservicebus__message_retry_total",
     "select": [
      [
       { "params": [ "rate5m" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "endpoint", "operator": "=~", "value": "/^$endpoint$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    },
    {
     "alias": "Failure Rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "nservicebus__message_failures",
     "select": [
      [
       { "params": [ "rate5m" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "endpoint", "operator": "=~", "value": "/^$endpoint$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    },
    {
     "alias": "Fetch Rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "nservicebus__messages_pulled_from_input_queue",
     "select": [
      [
       { "params": [ "rate5m" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "endpoint", "operator": "=~", "value": "/^$endpoint$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    },
    {
     "alias": "Success Rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "nservicebus__messages_successfully_processed",
     "select": [
      [
       { "params": [ "rate5m" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "endpoint", "operator": "=~", "value": "/^$endpoint$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Failure by Message Type",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_messagetype",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "messagetype" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "nservicebus__message_failures",
     "select": [
      [
       { "params": [ "rate5m" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "endpoint", "operator": "=~", "value": "/^$endpoint$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  }
 ]
}