trigger:
- master
- dev
- features/*

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - task: UseDotNet@2
    displayName: 'Install .NET Core SDK'
    inputs:
      packageType: 'sdk'
      useGlobalJson: true
  - task: Bash@3
    displayName: 'Build Script'
    inputs:
      targetType: filePath
      filePath: ./build.sh

- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - task: UseDotNet@2
    displayName: 'Install .NET Core 3.x SDK'
    inputs:
      packageType: 'sdk'
      useGlobalJson: true
  - task: PowerShell@2
    displayName: 'Build Script'
    inputs:
      targetType: filePath
      filePath: ./build.ps1
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Nuget Packages to Artifacts'
    inputs:
      PathtoPublish: 'nuget'